### ISSUE TITLE
Standing on the ground issue, dangerous taking off and landing

### ISSUE THREAD

**Issue by NightIntruder** [Seb105/Arma-Plane-Turbulence#2]
First of all - wonderful work, I really love the new feeling of flying brought by the mod. Thanks!
I would love to see the following improvements/changes:

a/ turbulences switched off or severely decreased when speed< 1
Exp: while a plane is standing on a runway/stand forces created by the mod looks weird, shaking a plane, usually up and down rather than in different directions. It may, however, be partially affected by my own script that calculates mass and refreshes it every 5 sec.

b/ turbulences in pitch removed up to 50m AGL (might be linear decrease).
Exp: during taking off and landing phase of flights often abrupt change in pitch creates a dangerous situation in-game. Winds going up and down over large flat areas at very low altitudes are not expected and almost non-existent IRL.

Please, refer to link with the recording from the test flight to see what I am talking about. The test flight was done with the mod's default settings as well as: overcast @ 80%, wind @ 63% and Guests @ 80% over Tanoa island. Max take off weight of the plane is app. 6100kG and that was the case during the test flight. I was dangerously pitched nose down twice during a difficult curved approach to St.George (on the footage below visible at app. 03:20 and 03:32).

https://youtu.be/92tlecwqdug

**Comment by NightIntruder** [comment]
By the way, I am not sure where to leave my "request" so will leave it here, in comments:
1. I would gladly accept a script/function that will control cam shaking for ppl onboard a plane during opening both gear (moderate shaking) and flaps (mild one), as well as touchdown. Obviously, the shaking - at least for gear and flaps - should be increasing and decreasing throughout a mechanism operation simulating changes in turbulent airflow around those things. It could actually become a part of turbulence mod, as it's somehow connected. What do you think? Not sure whether it would be easy to create a general function that would fit every plane, as the flaps and gear's opening time vary among addons but they all should have the times defined in their configs. They not may necceserally be relevant to the actual time of animation of flaps/gear.

**Comment by Seb105** [comment]
I'm not sure about the second point, but I can do something about vehicles being touched down.
